In [ ]:
import pandas as pd
import numpy as np

In [47]:
df = pd.DataFrame(pd.read_csv('/content/train (1).xls'))
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [32]:
df.shape

(891, 12)

In [33]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [34]:
drop_col = df.isnull().sum()[df.isnull().sum()>(35/100 * df.shape[0])]
drop_col

Cabin    687
dtype: int64

In [35]:
drop_col.index

Index(['Cabin'], dtype='object')

In [36]:
df.fillna(df.mean(), inplace=True)
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [37]:
df['Embarked'].describe()

count     889
unique      3
top         S
freq      644
Name: Embarked, dtype: object

In [38]:
df['Embarked'].fillna("S", inplace=True)
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [39]:
df.corr()

             PassengerId  Survived    Pclass  ...     SibSp     Parch      Fare
PassengerId     1.000000 -0.005007 -0.035144  ... -0.057527 -0.001652  0.012658
Survived       -0.005007  1.000000 -0.338481  ... -0.035322  0.081629  0.257307
Pclass         -0.035144 -0.338481  1.000000  ...  0.083081  0.018443 -0.549500
Age             0.033207 -0.069809 -0.331339  ... -0.232625 -0.179191  0.091566
SibSp          -0.057527 -0.035322  0.083081  ...  1.000000  0.414838  0.159651
Parch          -0.001652  0.081629  0.018443  ...  0.414838  1.000000  0.216225
Fare            0.012658  0.257307 -0.549500  ...  0.159651  0.216225  1.000000

[7 rows x 7 columns]

In [40]:
df['FamilyMan'] = df['SibSp'] + df['Parch']
df.drop(['SibSp', 'Parch'], axis=1, inplace=True)
df.corr()

             PassengerId  Survived    Pclass       Age      Fare  FamilyMan
PassengerId     1.000000 -0.005007 -0.035144  0.033207  0.012658  -0.040143
Survived       -0.005007  1.000000 -0.338481 -0.069809  0.257307   0.016639
Pclass         -0.035144 -0.338481  1.000000 -0.331339 -0.549500   0.065997
Age             0.033207 -0.069809 -0.331339  1.000000  0.091566  -0.248512
Fare            0.012658  0.257307 -0.549500  0.091566  1.000000   0.217138
FamilyMan      -0.040143  0.016639  0.065997 -0.248512  0.217138   1.000000

In [41]:
df['SinglePerson'] = [0 if df['FamilyMan'][i]>0 else 1 for i in df.index]
df.head()

   PassengerId  Survived  Pclass  ... Embarked FamilyMan  SinglePerson
0            1         0       3  ...        S         1             0
1            2         1       1  ...        C         1             0
2            3         1       3  ...        S         0             1
3            4         1       1  ...        S         1             0
4            5         0       3  ...        S         0             1

[5 rows x 12 columns]

In [42]:
df.groupby(['SinglePerson'])['Survived'].mean()

SinglePerson
0    0.505650
1    0.303538
Name: Survived, dtype: float64

In [43]:
df[['SinglePerson', 'Fare']].corr()

              SinglePerson      Fare
SinglePerson      1.000000 -0.271832
Fare             -0.271832  1.000000

In [44]:
df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index] 
#Note: 0 is for Male and 1 is for FeMale
df.groupby(['Sex'])['Survived'].mean()

Sex
0    0.188908
1    0.742038
Name: Survived, dtype: float64

In [45]:
df.groupby(['Embarked'])['Survived'].mean()

Embarked
C    0.553571
Q    0.389610
S    0.339009
Name: Survived, dtype: float64

Conclusion: -

1.Female passengers were given priority in escaping the sinking ship over male passengers.
2.The World's Shocking Reality, The wealthy have a greater survival rate than the rest of the population.
3.Passengers who go with their families have a greater survival rate.
4.Passengers that boarded the ship at Cherbourg fared better in proprtions than others, indicating that they were either extremely fortunate or that it was their fate.